### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by christianhoward**
Grammatical changes/updates.

### CODE REVIEW

**Comment by curiouslychase** [comment]
@tiagoporto, fwiw, this is the best of the 3.

**Comment by tiagoporto** [comment]
Thanks @christianhoward, please just resolve the conflicts to merge this PR.

**Comment by christianhoward** [comment]
@tiagoporto I'm not sure how to resolve on github. How do I go about doing this?

**Comment by christianhoward** [comment]
@tiagoporto I think I've made the correct updates. Please confirm.

**Comment by tiagoporto** [comment]
The message remains, This branch has conflicts that must be resolved.

**Comment by christianhoward** [comment]
@tiagoporto I can't see those conflicts. Can you tell me what they are so that I can attend to them?

**Comment by tiagoporto** [comment]
I merged this manually, thanks.

**Pull request merged**
